### ISSUE TITLE
Unique Feature of Omnipause

### ISSUE THREAD

**Issue by lieb005** [mel00010/OmniPause#1]
Hello, I see the README says that you think that playerctl does everything your script does, but as far as I know, your script is the only one I have been able to find so far that can pause all players /and resume the one that was previously playing/.  I had been looking for something like this for at least a year (my bash scripts around playerctl always got way too complicated and never fully worked), and I just want to say your work is valuable! Thank you!

**Comment by mel00010** [comment]
Thanks for the feedback!  I'm glad you appreciate the project.  I use it almost every day, so I'm glad that you can find some use out of it too.
